import { StyleSheet, Dimensions, Platform } from "react-native";

export const myStyles = StyleSheet.create({
   rootContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DEC5E3",
  },   
  backgroundImage: {
    opacity: 1,
  },
  titleContainer: {
    flex: 1,
    width: "80%",
    backgroundColor: "#CDEDFD",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderRadius: 10,
    borderColor: "#B6DCFE",
    marginBottom: 10,
    marginHorizontal: 20,
  },
  text: {
    color: "white",
    fontSize: 24,
    letterSpacing: 2,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 5,
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    lineHeight: 55,
    fontFamily: "HolidayIsland",
  },
  navbuttonContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navButton: {
    marginHorizontal: 10,
  },
  scrollContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
  },
  rowContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
    margin: 5,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingBottom: 20,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  centeredModalView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "#A9F8FB",
    borderColor: "#B6DCFE",
    borderWidth: 4,
    borderRadius: 10,
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    elevation: 5,
  },
  gridItem: {
    flex: 1, 
    margin: 8,  
    aspectRatio: 1,  
    width: "80%", 
    borderRadius: 8,
    elevation: 4, 
    backgroundColor: "white",
    shadowColor: "black",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  button: {
    flex: 1,
  },
  innerContainer: {
    flex: 1,
    padding: 0,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  name: {
    textAlign: "center",
    fontSize: 25,
    fontFamily: "HolidayIsland",
    fontWeight: "bold",
  },
  itemContainer: {
    backgroundColor: "#DEC5E3",
    paddingHorizontal: 5,
    paddingTop: 3,
    marginBottom: 3,
    borderRadius: 7,
  },
  buttonPressed: {
    opacity: 0.5
  },
  image: {
    width: "25%",
    height: "100%",
    resizeMode: "contain",
    borderRadius: 15,
  },
  infoContainer: {
    width: "75%",
    paddingLeft: 20,
  },
  cost: {
    width: "85%",
    fontSize: 14,
  },
  year: {
    fontSize: 14,
    fontWeight: "bold"
  },
  innerRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rating: {
    fontSize: 13,
    fontStyle: "italic",
  },
  container: {
    flex: 1,
    padding: 16,
  },
  listContainer: {
    flex: 2,
    width: 3000,
    maxWidth: "100%",
    height: 3000,
    maxHeight: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
});