import { StyleSheet, Dimensions, Platform } from "react-native";

export const myStyles = StyleSheet.create({
   rootContainer: {
    flex: 1,
    maxWidth: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DEC5E3",
  },   
  root2Container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },   
  backgroundImage: {
    opacity: 1,
  },
  titleContainer: {
    flex: 1,
    width: "80%",
    backgroundColor: "#CDEDFD",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderRadius: 10,
    borderColor: "#B6DCFE",
    marginBottom: 10,
    marginHorizontal: 20,
  },
  text: {
    color: "white",
    fontSize: 24,
    letterSpacing: 2,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 5,
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    lineHeight: 55,
    fontFamily: "HolidayIsland",
  },
  infoText: {
    color: "white",
    fontSize: 23,
    letterSpacing: 3,
    fontWeight: "600",
    textAlign: "center",
    marginVertical: 5,
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    lineHeight: 22,
    fontFamily: "HolidayIsland",
  },
  navbuttonContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navButton: {
    marginHorizontal: 10,
  },
  scrollContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
  },
  rowContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
    margin: 5,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingBottom: 20,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  columnContainer: {
    flex: 1,
    width: 3000,
    maxWidth: "100%",
    flexDirection: "column",
    flexWrap: "wrap",
    justifyContent: "space-around",
    alignItems: "center",
  },
  centeredModalView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "#A9F8FB",
    borderColor: "#B6DCFE",
    borderWidth: 4,
    borderRadius: 10,
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    elevation: 5,
  },
  gridItem: {
    flex: 1, 
    margin: 8,  
    aspectRatio: 1,  
    width: "80%", 
    borderRadius: 8,
    elevation: 4, 
    backgroundColor: "white",
    shadowColor: "black",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  button: {
    flex: 1,
  },
  innerContainer: {
    flex: 1,
    padding: 0,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  name: {
    textAlign: "center",
    fontSize: 25,
    fontFamily: "HolidayIsland",
    fontWeight: "bold",
  },
  itemContainer: {
    maxWidth: "100%",
    backgroundColor: "#DEC5E3",
    paddingHorizontal: 5,
    paddingTop: 3,
    marginBottom: 3,
    borderRadius: 7,
  },
  buttonPressed: {
    opacity: 0.5
  },
  imageContainer: {
    flex: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  image: {
    width: 350,
    height: "100%",
    borderRadius: 15,
    borderColor: "white",
    borderWidth: 5,
    resizeMode: "cover",
  },
  infoContainer1: {
    flex: 5,
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  infoContainer: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  infoContainer2: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  cost: {
    width: "85%",
    fontSize: 14,
  },
  year: {
    fontSize: 14,
    fontWeight: "bold"
  },
  innerRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  innerColumnContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap"
  },
  rating: {
    fontSize: 13,
    fontStyle: "italic",
  },
  container: {
    flex: 3,
    padding: 16,
  },
  listContainer: {
    flex: 4,
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "#CDEDFD",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderRadius: 10,
    borderColor: "#B6DCFE",
    marginBottom: 10,
    marginHorizontal: 20,
  },
  list2Container: {
    flex: 4,
    maxWidth: "100%",
    width: 300,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "#CDEDFD",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderRadius: 10,
    borderColor: "#B6DCFE",
    marginBottom: 10,
    marginHorizontal: 20,
  },
  list3container: {
    flex: 2,
    width: 3000,
    maxWidth: "100%",
    height: 3000,
    maxHeight: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  input: {
    height: 45,
    marginVertical: 8,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: 'black',
    backgroundColor: 'white',
    fontFamily: "HolidayIsland",
  },
  
  header: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  inputContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  taskContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 10,
    marginBottom: 10,
    borderRadius: 5,
    elevation: 2,
  },
  taskText: {
    paddingHorizontal: 12,
    fontSize: 16,
    color: 'black',
    backgroundColor: 'white',
    fontFamily: "HolidayIsland",
  },
  completedText: {
    textDecorationLine: "line-through",
    color: "gray",
    fontFamily: "HolidayIsland",
  },
  deleteButton: {
    marginLeft: 10,
  },
  deleteText: {
    fontSize: 18,
    color: "red",
    fontFamily: "HolidayIsland",
  },
});