import { StyleSheet } from "react-native";

export const myStyles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: "#FAF3DD",
    alignItems: "center",
    justifyContent: "center",
  },
  titleContainer: {
    flex: 1,
    backgroundColor: "#8B0000",
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    borderWidth: 3,
    borderRadius: 10,
    borderColor: "#8B0000",
    marginVertical: 10,
  },
  imageContainer: {
    flex: 3,
    width: "90%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    marginVertical: 10,
  },
  image: {
    height: 320,
    width: "100%",
    resizeMode: "cover",
    borderWidth: 4,
    borderColor: "#8B0000",
    borderRadius: 10,
  },
  informationContainer: {
    flex: 2,
    width: "90%",
    backgroundColor: "#006400",
    borderWidth: 3,
    borderColor: "#8B0000",
    borderRadius: 10,
    padding: 15,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  listContainer: {
    flex: 5,
    padding: 10,
    paddingHorizontal: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  text: {
    color: "#FAF3DD",
    fontSize: 24,
    letterSpacing: 2,
    fontWeight: "600",
    fontFamily: "Barlock",
    textAlign: "center",
    marginVertical: 5,
    textShadowColor: "#8B0000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
    lineHeight: 55,
  },
  buttonContainer: {
    backgroundColor: "#FFD700",
    borderWidth: 3,
    borderColor: "#8B0000",
    borderRadius: 10,
    padding: 5,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  buttonText: {
    color: "#006400",
    fontSize: 25,
    letterSpacing: 2,
    fontWeight: "600",
    fontFamily: "Barlock",
    textAlign: "center",
    marginVertical: 5,
    textShadowColor: "white",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
  },
});